### ISSUE TITLE
No way to damage surface in Wayland

### ISSUE THREAD

**Issue by i509VCB** [rust-windowing/softbuffer#9] opened 2022-05-31 19:35 UTC
Many compositors implement damage tracking, meaning that commiting a new buffer when calling set_buffer does nothing.

A proper fix would involve the caller giving the implementation a set of rectangles where content has changed.

**Comment by john01dav** [comment] 2022-12-22 23:55
Closing as duplicate of #39 with the merge of swbuf and softbuffer

**Closed by john01dav** 2022-12-22 23:55 UTC
