### ISSUE TITLE
Tests for Windows under GNU are experiencing a linker failure

### ISSUE THREAD

**Issue by notgull** [rust-windowing/softbuffer#142] opened 2023-08-28 04:25 UTC
Taken from the latest CI logs:

```
          Warning: .drectve `-exclude-symbols:_ZN17raw_window_handle8borrowed3imp6Active6handle17hcdc9a7e46fa42377E ' unrecognized
          Warning: .drectve `-exclude-symbols:_ZN17raw_window_handle8borrowed3imp6Active10set_active17h87aab7a0dbfa799aE ' unrecognized
          Warning: .drectve `-exclude-symbols:_ZN17raw_window_handle8borrowed3imp6Active12set_inactive17hdc388a803d443f6fE ' unrecognized
          Warning: .drectve `-exclude-symbols:_ZN17raw_window_handle8borrowed3imp12ActiveHandle13new_unchecked17h717ec49c81207b3aE ' unrecognized
          Warning: corrupt .drectve at end of def file
          Warning: corrupt .drectve at end of def file
          Warning: corrupt .drectve at end of def file
          Warning: corrupt .drectve at end of def file
          collect2.exe: error: ld returned 5 exit status
```

This failure only occurs for `*-pc-windows-gnu`, not `*-pc-windows-msvc`. Also it apparently only happens under Windows, as I can build it for `x86_64-pc-windows-gnu` just fine on my Linux laptop.

I need to go to bed now, but I'll investigate this on my Windows VM this week.

**Comment by ids1024** [comment] 2023-09-08 05:45
I'm guessing this is an issue with how the build environment is set up on CI and not really a Softbuffer issue... still haven't booted into Windows and tried to reproduce it though.

I previously had weird compile issues in a project with the Windows gnu toolchain running under msys2 with a Rust install from outside msys2; which was fixed by just using msys2's version of Rust. Some weird compile error started happening that hadn't before, but I don't remember if it was like this one: https://github.com/pop-os/keyboard-configurator/commit/0b5827a00f74e2dd48750a2ffeda2546e009092e.

**Comment by ids1024** [comment] 2023-09-08 05:49
Looking up the error, it looks like these warnings would happen if the libraries were built with msvc, but linked with gnu ld, which doesn't use that directive? Not sure why that would be happening.

**Comment by ids1024** [comment] 2023-09-08 05:57
Ah: https://github.com/rust-lang/rust/issues/112368. Looks like the warnings appear starting in Rust 1.70, which updates LLVM to have https://github.com/llvm/llvm-project/commit/c5b3de6745c37dd991430b9b88ff97c35b6fc455. The directive would be supported with a sufficiently new version of ld or lld. *But* it should just be a warning and work anyway?

It's not obvious to my looking at the logs why this is causing a compile failure. All the messages the linker is printing are warnings.

Anyway, it doesn't seem to be a Softbuffer issue, and would occur with any Rust code built in the same environment. I guess...

**Comment by ids1024** [comment] 2023-09-08 16:31
https://github.com/microsoft/windows-rs/issues/2614#issuecomment-1684152597

I guess the problem is that ld is crashing, not erroring, with nothing useful logged? But it shouldn't be an issue with newer versions of ld.

In any case, not really softbuffer related.

**Closed** 2023-09-09 20:40 UTC
